# Generated by Django 4.1.7 on 2023-02-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(max_length=5)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_branch', models.CharField(max_length=20)),
            ],
        ),
    ]
